[supervisord]
nodaemon=true
user=root
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:redis]
command=redis-server --bind 0.0.0.0 --port 6379 --dir /var/lib/redis --protected-mode no
autostart=true
autorestart=true
user=root
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=90
startsecs=5
startretries=3

[program:api]
command=/app/server/monitoring api
directory=/app/server
autostart=true
autorestart=true
user=root
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=DB_TYPE="sqlite",DB_NAME="/app/data/peekaping.db",REDIS_HOST="0.0.0.0",REDIS_PORT="6379",MODE="prod",SERVER_PORT="8383"
priority=100
startsecs=10
startretries=3

[program:engine]
command=/app/server/monitoring engine
directory=/app/server
autostart=true
autorestart=true
user=root
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=DB_TYPE="sqlite",DB_NAME="/app/data/peekaping.db",REDIS_HOST="0.0.0.0",REDIS_PORT="6379",MODE="prod"
priority=110
startsecs=10
startretries=3

